const Images = {
  cart: require('../assets/Images/add-cart.png'),
  foods: require('../assets/Images/fast-food.png'),
  bills: require('../assets/Images/invoice.png'),
  plus: require('../assets/Images/plus.png'),
  car: require('../assets/Images/sports-car.png'),
  spy: require('../assets/Images/spy.png'),
  logo: require('../assets/Images/logos.png'),
  // theepa: require('../assets/Images/logo2.png'),
  theepa: require('../assets/Images/theepa.png'),
  logoname: require('../assets/Images/logoname.png'),
  user: require('../assets/Images/user.png'),
  lock: require('../assets/Images/lock.png'),
  bell: require('../assets/Images/bell.png'),
  visa: require('../assets/Images/visa.png'),
  // ui updated below
  cross: require('../assets/Images/cross.png'),
  calendar: require('../assets/Images/calendar.png'),
  dropdown: require('../assets/Images/dropdown.png'),
  bills: require('../assets/Images/bills.png'),
  clothes: require('../assets/Images/clothes.png'),
  food: require('../assets/Images/food.png'),
  grocery: require('../assets/Images/grocery.png'),
  petrol: require('../assets/Images/petrol.png'),
  add: require('../assets/Images/add.png'),
  meezan: require('../assets/Images/meezan.png'),
  alhabib: require('../assets/Images/alhabib.png'),
  allied: require('../assets/Images/Allied.png'),
  BOP: require('../assets/Images/BOP.png'),
  HBL: require('../assets/Images/HBL.png'),
  filter: require('../assets/Images/filter.png'),
  edit: require('../assets/Images/edit.png'),
  left: require('../assets/Images/left.png'),
  entertainment: require('../assets/Images/Entertainment.png'),
  home: require('../assets/Images/Home.png'),
  income: require('../assets/Images/Income.png'),
  insurance: require('../assets/Images/Insurance.png'),
  medicine: require('../assets/Images/Medicine.png'),
  misc: require('../assets/Images/Misc.png'),
  spending: require('../assets/Images/Spending.png'),
  transport: require('../assets/Images/Transport.png'),
  goal: require('../assets/Images/goal.png'),
  locker: require('../assets/Images/locker.png'),
  eyeIcon: require('../assets/Images/Visibility.png'),
  googleicon: require('../assets/Images/Google.png'),
  facebookicon: require('../assets/Images/FBLogo.png'),
  delete: require('../assets/Images/delete.png'),
  bankicon: require('../assets/Images/BankAccountSettingsIcon18px.png'),
  categoryicon: require('../assets/Images/CategoryIcon18px.png'),
  abouticon: require('../assets/Images/AboutIcon18px.png'),
  contacticon: require('../assets/Images/ContactIcon18px.png'),
  helpicon: require('../assets/Images/HelpIcon18px.png'),
  settingsicon: require('../assets/Images/SettingsIcon18px.png'),
  usericon: require('../assets/Images/AccountsIcon18px.png'),
  addincomeicon: require('../assets/Images/Vector.png'),
  addexpenseicon: require('../assets/Images/expensetag.png'),
  editicon: require('../assets/Images/EditTextIcon24px.png'),
  allbanksicon: require('../assets/Images/BankIcon03.png'),
  allbanksicon2: require('../assets/Images/bankicon2.png'),
  allbanksiconHome: require('../assets/Images/BankIconHome.png'),
  onboarding: require('../assets/Images/onboarding.png'),
  arrowup: require('../assets/Images/arrowup.png'),
  questionmark: require('../assets/Images/questionmark.png'),
  dubaibank: require('../assets/Images/dubaibank.png'),
};

export default Images;
